[theme]
primaryColor = "#0d99ad"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1c2128"
textColor = "#e0e0e0"
font = "sans serif"

[client]
showErrorDetails = true
showWarningOnDirectExecution = false

[logger]
level = "info"

[server]
headless = true
runOnSave = true
port = 8501
